---
- name: Restart exit WireGuard transit
  ansible.builtin.service:
    name: "wg-quick@{{ exit_wg_transit_interface }}"
    enabled: true
    state: restarted
  when: not ansible_check_mode

- name: Restart exit exit-full WireGuard
  ansible.builtin.service:
    name: "wg-quick@{{ exit_entry_full_wg_interface }}"
    enabled: true
    state: restarted
  when:
    - exit_entry_full_enabled
    - not ansible_check_mode

- name: Validate nftables before reload
  ansible.builtin.command: nft -c -f /etc/nftables.conf
  changed_when: false
  listen: Reload nftables

- name: Reload nftables service
  ansible.builtin.service:
    name: nftables
    state: reloaded
  listen: Reload nftables
