ansible_ssh_private_key_file: ~/.ssh/yc_vm_ed25519

host_notes:
  os: Ubuntu 24.04.4 LTS
  vm_name: yandex-wg-direct
  public_ip: 89.169.158.239
  ssh_user: yc-user
  ssh_key: ~/.ssh/yc_vm_ed25519

yandex_direct_wg_client_interface: wg0
yandex_direct_wg_client_address: 10.80.0.1/24
yandex_direct_wg_client_listen_port: 51944
yandex_direct_client_cidr: 10.80.0.0/24
yandex_direct_wg_client_private_key_path: "/Users/nmel/.config/vpn-gen/wireguard-direct-yandex/server.private.key"
yandex_direct_wg_client_peers:
  - name: direct-client
    public_key: "uqLgsAil5pLPf+d7UWRfNSWDfUqE4/TsDX1LZKZgumA="
    allowed_ips:
      - "10.80.0.10/32"

yandex_direct_wg_transit_interface: wg-transit
yandex_direct_wg_transit_address: 10.91.0.1/32
yandex_direct_wg_transit_listen_port: 51945
yandex_direct_wg_transit_private_key_path: "/Users/nmel/.config/vpn-gen/wireguard-direct-yandex/yandex_transit.private.key"
yandex_direct_policy_table: 210
yandex_direct_policy_rule_priority: 210

yandex_direct_racknerd_public_key: "h1TN7ERqzQ4GpRxhLKMc1RpzV4GX/8kYp2MTUFx78k8="
yandex_direct_racknerd_endpoint: "172.245.154.109:51946"
yandex_direct_racknerd_transit_address: "10.91.0.2/32"
yandex_direct_racknerd_allowed_ips:
  - "0.0.0.0/0"
yandex_direct_racknerd_persistent_keepalive: 25
