---
- name: Restart Yandex WireGuard client
  ansible.builtin.service:
    name: "wg-quick@{{ yandex_edge_wg_client_interface }}"
    enabled: true
    state: restarted

- name: Restart Yandex WireGuard transit
  ansible.builtin.service:
    name: "wg-quick@{{ yandex_edge_wg_transit_interface }}"
    enabled: true
    state: restarted

- name: Validate nftables before reload
  ansible.builtin.command: nft -c -f /etc/nftables.conf
  changed_when: false
  listen: Reload nftables

- name: Reload nftables service
  ansible.builtin.service:
    name: nftables
    state: reloaded
  listen: Reload nftables
