all:
  children:
    yandex_cloud:
      hosts:
        yc_ubuntu_2404_min:
          ansible_host: 111.88.242.229
          internal_ip: 10.128.0.24
          cloud_provider: yandex_cloud
          cloud_instance_id: fhmos8q6ok3e7chqhj7q
          cloud_zone: ru-central1-a
    external_vps:
      hosts:
        racknerd_ubuntu:
          ansible_host: 172.245.154.109
          cloud_provider: racknerd
