all:
  children:
    entry:
      children:
        entry_split:
          hosts:
            entry_split_01:
        entry_full:
          hosts:
            entry_full_01:
      vars:
        node_role: entry
    entry_split:
      hosts:
        entry_split_01:
          ansible_host: 51.250.14.221
          internal_ip: 10.128.0.24
          cloud_instance_id: fhmos8q6ok3e7chqhj7q
          cloud_instance_name: entry-split-01
          cloud_zone: ru-central1-a
    entry_full:
      hosts:
        entry_full_01:
          ansible_host: 89.169.158.239
          ansible_user: yc-user
          internal_ip: 10.128.0.22
          cloud_instance_id: fhm3c045jsjooimks0ri
          cloud_instance_name: entry-full-01
          cloud_zone: ru-central1-a
    exit:
      hosts:
        exit_01:
          ansible_host: 172.245.154.109
          node_role: exit
