all:
  children:
    entry:
      children:
        entry_split:
          hosts:
            entry_split_01:
        entry_full:
          hosts:
            entry_full_01:
      vars:
        node_role: entry
    entry_split:
      hosts:
        entry_split_01:
          ansible_host: "{{ vpn_gen_entry_split_host }}"
    entry_full:
      hosts:
        entry_full_01:
          ansible_host: "{{ vpn_gen_entry_full_host }}"
    exit:
      hosts:
        exit_01:
          ansible_host: "{{ vpn_gen_exit_host }}"
          node_role: exit
        exit_02:
          ansible_host: "{{ vpn_gen_exit2_host }}"
          node_role: exit
