---
- name: Restart Yandex direct client
  ansible.builtin.service:
    name: "wg-quick@{{ yandex_direct_wg_client_interface }}"
    state: restarted
  when: not ansible_check_mode

- name: Restart Yandex direct transit
  ansible.builtin.service:
    name: "wg-quick@{{ yandex_direct_wg_transit_interface }}"
    state: restarted
  when: not ansible_check_mode

- name: Validate nftables before reload
  ansible.builtin.command: nft -c -f "{{ yandex_direct_nftables_conf }}"
  changed_when: false
  listen: Reload nftables

- name: Reload nftables service
  ansible.builtin.service:
    name: nftables
    state: reloaded
  listen: Reload nftables
  when: not ansible_check_mode
