---
yandex_direct_wg_client_interface: wg0
yandex_direct_wg_client_address: 10.80.0.1/24
yandex_direct_wg_client_listen_port: 51944
yandex_direct_wg_client_private_key: ""
yandex_direct_wg_client_private_key_path: ""
yandex_direct_wg_client_peers: []

yandex_direct_wg_transit_interface: wg-transit
yandex_direct_wg_transit_address: 10.91.0.1/32
yandex_direct_wg_transit_listen_port: 51945
yandex_direct_wg_transit_private_key: ""
yandex_direct_wg_transit_private_key_path: ""

yandex_direct_racknerd_public_key: ""
yandex_direct_racknerd_endpoint: "172.245.154.109:51946"
yandex_direct_racknerd_allowed_ips:
  - "0.0.0.0/0"
yandex_direct_racknerd_persistent_keepalive: 25
yandex_direct_racknerd_transit_address: "10.91.0.2/32"

yandex_direct_client_cidr: 10.80.0.0/24
yandex_direct_public_interface: eth0
yandex_direct_policy_table: 210
yandex_direct_policy_rule_priority: 210
yandex_direct_nftables_conf: /etc/nftables.conf
